---
# tasks file for nginx
  - name: install nginx
    yum: 
      name: nginx
      state: present
      update_cache: yes

  - name: de-activate default nginx site (update nginx.conf)
    copy: 
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      mode: 0644
      force: yes 
    notify: restart nginx
    
  - name: get other nginx sites
    shell: ls -1 /etc/nginx/conf.d/
    register: active
    
  - name: de-activate other nginx sites
    file: path=/etc/nginx/conf.d/{{ item }} state=absent
    with_items: "{{ active.stdout_lines }}"
    when: item not in sites
    notify: restart nginx
  
  - name: configure nginx new site
    template: 
      src: demo.nginx.conf.j2
      dest: /etc/nginx/conf.d/{{ item.key }}.conf
      mode: 0644
    with_dict: 
      - "{{ sites }}"
    notify: restart nginx
     
  - name: ensure nginx started
    service: 
      name: nginx
      state: started
      enabled: yes