---
# tasks file for demo_app
  - name: enable proxy cntlm
    command: systemctl start cntlm
    tags:
      - packages
    
  - name: install web components
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
      skip_broken: yes
    vars:
      packages:
        - python-devel
        - python-setuptools
        - python-pip
        - MySQL-python
        - python-httplib2
    tags:
      - packages
        
  - name: install pip
    command: pip install -U pip
    tags:
      - packages
    
  - name: install virtualenv
    command: pip install -U virtualenv
    tags:
      - packages
    
  - name: copy demo app source
    copy: src=demo/app/ dest=/var/www/demo mode=0755
    notify: restart httpd
    tags:
      - configure
    
  - name: copy demo app wsgi file
    template: src=demo.wsgi.j2 dest=/var/www/demo/demo.wsgi
    notify: restart httpd
    tags:
      - configure
    
  - name: copy httpd virtualhost config
    copy: src=demo/demo.conf dest=/etc/httpd/sites-avaiable mode=0755
    notify: restart httpd
    tags:
      - configure
         
  - name: activate demo site
    file: src=/etc/httpd/sites-avaiable/demo.conf dest=/etc/httpd/conf.d/demo.conf state=link
    notify: restart httpd
    tags:
      - configure
    
  - name: python virtual environment
    pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
    notify: restart httpd
    tags:
      - system
    
  - name: disable proxy cntlm
    command: systemctl stop cntlm
    tags:
      - packages