---
  - hosts: loadbalancer
    become: true
    tasks: 
    - name: verify nginx status
      command: systemctl status nginx
    - name: verify nginx is listening on 80
      wait_for:
        port: 80
        timeout: 1
      
  - hosts: webserver
    become: true
    tasks: 
    - name: verify httpd status
      command: systemctl status httpd
    - name: verify httpd is listening on 80
      wait_for: 
        port: 80
        timeout: 1
      
  - hosts: database
    become: true
    tasks: 
    - name: verify mariadb status
      command: systemctl status mariadb
      
    - name: verify mariadb is listening on 3306
      wait_for: 
        host: "{{ ansible_eth0.ipv4.address }}"
        port: 3306 
        timeout: 1
      
  - hosts: control
    become: true
    tasks:
    - name: verify end-to-end response
      uri: 
        url: "http://{{ item }}"
        return_content: yes
      with_items: "{{ groups['loadbalancer'] }}"
      register: lb_index
      environment: 
        http_proxy: ""
        https_proxy: ""
    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{ lb_index.results }}"
      
  - hosts: loadbalancer
    become: true
    tasks:
    - name: verify backend response
      uri: url=http://{{ item }} return_content=yes
      with_items: "{{ groups['webserver'] }}"
      register: app_index
      environment: 
        http_proxy: ""
        https_proxy: ""
    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{ app_index.results }}"
      
    - name: verify backend db response
      uri: url=http://{{ item }}/db return_content=yes
      with_items: "{{ groups['webserver'] }}"
      register: db_index
      environment: 
        http_proxy: ""
        https_proxy: ""
    - fail: msg="db failed to return content"
      when: "'Database Connected' not in item.content"
      with_items: "{{ db_index.results }}"