---
# tasks file for mariadb
  - name: install tools
    yum: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - MySQL-python
  
  - name: install mariadb-server
    yum: 
      name: mariadb-server
      state: present
      update_cache: yes

  - name: ensure mmariadb configuration to listen on instance IP
    lineinfile: 
      dest: /etc/my.cnf.d/server.cnf
      regexp: "^bind"
      line: "bind = {{ ansible_eth0.ipv4.address }}"
    notify: restart mariadb
      
  - name: ensure mariadb started
    service: name=mariadb state=started enabled=yes

  - name: create database
    mysql_db: name={{ db_name }} state=present
    
  - name: create database user
    mysql_user: name={{ db_username }} password={{ db_userpass }} priv={{ db_name }}.*:ALL host='{{ db_userhost }}' state=present